version: "3.9"
services:
  nginx_php:
    build:
      context: .
      dockerfile: Dockerfile
    image: thinkphp
    restart: on-failure
    volumes:
      - ./src:/var/www/html/thinking
    ports:
      - "30006:8000"
    depends_on:
      - mysql
    networks:
      - lnmp_net

  mysql:
    image: mysql:5.6.51
    expose:
      - "3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=tpdata
    networks:
      - lnmp_net

networks:
  lnmp_net:
    name: lnmp
